### ISSUE TITLE
issue starting nix in tutorial 

### ISSUE THREAD

**Issue by tamingchaos** [vfarcic/crossplane-tutorial#23]
almost certainly not your issue @vfarcic, but though you should know this bug is breaking your tutorial (at least on my mac)

`
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/qw0lb7a2yk1lix39yp02mhlmwxaxxlf2-fabric-3.2.2.tar.gz
source root is fabric-3.2.2
setting SOURCE_DATE_EPOCH to timestamp 1693446095 of file fabric-3.2.2/setup.cfg
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
substituteStream() in derivation python3.12-fabric-3.2.2: WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'setup.py')
substituteStream() in derivation python3.12-fabric-3.2.2: WARNING: pattern \,\ \"pathlib2\" doesn't match anything in file 'setup.py'
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Executing setuptoolsBuildPhase
/nix/store/q0kn7bj2zfqhlqrpphwqrn4sv5789cps-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/dist.py:268: UserWarning: Unknown distribution option: 'python_requres'
  warnings.warn(msg)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/fabric
copying fabric/auth.py -> build/lib/fabric
copying fabric/tunnels.py -> build/lib/fabric
copying fabric/tasks.py -> build/lib/fabric
copying fabric/config.py -> build/lib/fabric
copying fabric/_version.py -> build/lib/fabric
copying fabric/util.py -> build/lib/fabric
copying fabric/__init__.py -> build/lib/fabric
copying fabric/connection.py -> build/lib/fabric
copying fabric/transfer.py -> build/lib/fabric
copying fabric/runners.py -> build/lib/fabric
copying fabric/group.py -> build/lib/fabric
copying fabric/exceptions.py -> build/lib/fabric
copying fabric/main.py -> build/lib/fabric
copying fabric/__main__.py -> build/lib/fabric
copying fabric/executor.py -> build/lib/fabric
creating build/lib/fabric/testing
copying fabric/testing/__init__.py -> build/lib/fabric/testing
copying fabric/testing/base.py -> build/lib/fabric/testing
copying fabric/testing/fixtures.py -> build/lib/fabric/testing
/nix/store/q0kn7bj2zfqhlqrpphwqrn4sv5789cps-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
installing to build/bdist.macosx-11.0-arm64/wheel
running install
running install_lib
creating build/bdist.macosx-11.0-arm64
creating build/bdist.macosx-11.0-arm64/wheel
creating build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/auth.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/tunnels.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/tasks.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/config.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/_version.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/util.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/__init__.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
creating build/bdist.macosx-11.0-arm64/wheel/fabric/testing
copying build/lib/fabric/testing/__init__.py -> build/bdist.macosx-11.0-arm64/wheel/fabric/testing
copying build/lib/fabric/testing/base.py -> build/bdist.macosx-11.0-arm64/wheel/fabric/testing
copying build/lib/fabric/testing/fixtures.py -> build/bdist.macosx-11.0-arm64/wheel/fabric/testing
copying build/lib/fabric/connection.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/transfer.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/runners.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/group.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/exceptions.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/main.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/__main__.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
copying build/lib/fabric/executor.py -> build/bdist.macosx-11.0-arm64/wheel/fabric
running install_egg_info
running egg_info
writing fabric.egg-info/PKG-INFO
writing dependency_links to fabric.egg-info/dependency_links.txt
writing entry points to fabric.egg-info/entry_points.txt
writing requirements to fabric.egg-info/requires.txt
writing top-level names to fabric.egg-info/top_level.txt
reading manifest file 'fabric.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'sites/*/_build'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'integration'
warning: no previously-included files matching '*.pyo' found under directory 'integration'
adding license file 'LICENSE'
writing manifest file 'fabric.egg-info/SOURCES.txt'
Copying fabric.egg-info to build/bdist.macosx-11.0-arm64/wheel/fabric-3.2.2-py3.12.egg-info
running install_scripts
creating build/bdist.macosx-11.0-arm64/wheel/fabric-3.2.2.dist-info/WHEEL
creating 'dist/fabric-3.2.2-py3-none-any.whl' and adding 'build/bdist.macosx-11.0-arm64/wheel' to it
adding 'fabric/__init__.py'
adding 'fabric/__main__.py'
adding 'fabric/_version.py'
adding 'fabric/auth.py'
adding 'fabric/config.py'
adding 'fabric/connection.py'
adding 'fabric/exceptions.py'
adding 'fabric/executor.py'
adding 'fabric/group.py'
adding 'fabric/main.py'
adding 'fabric/runners.py'
adding 'fabric/tasks.py'
adding 'fabric/transfer.py'
adding 'fabric/tunnels.py'
adding 'fabric/util.py'
adding 'fabric/testing/__init__.py'
adding 'fabric/testing/base.py'
adding 'fabric/testing/fixtures.py'
adding 'fabric-3.2.2.dist-info/LICENSE'
adding 'fabric-3.2.2.dist-info/METADATA'
adding 'fabric-3.2.2.dist-info/WHEEL'
adding 'fabric-3.2.2.dist-info/entry_points.txt'
adding 'fabric-3.2.2.dist-info/top_level.txt'
adding 'fabric-3.2.2.dist-info/RECORD'
removing build/bdist.macosx-11.0-arm64/wheel
Finished executing setuptoolsBuildPhase
Running phase: installPhase
@nix { "action": "setPhase", "phase": "installPhase" }
Executing pypaInstallPhase
Successfully installed fabric-3.2.2-py3-none-any.whl
Finished executing pypaInstallPhase
Running phase: pythonOutputDistPhase
@nix { "action": "setPhase", "phase": "pythonOutputDistPhase" }
Executing pythonOutputDistPhase
Finished executing pythonOutputDistPhase
Running phase: fixupPhase
@nix { "action": "setPhase", "phase": "fixupPhase" }
checking for references to /private/tmp/nix-build-python3.12-fabric-3.2.2.drv-0/ in /nix/store/c10n2rxk9rgd6mh9nal9d5jv8q3ic32f-python3.12-fabric-3.2.2...
patching script interpreter paths in /nix/store/c10n2rxk9rgd6mh9nal9d5jv8q3ic32f-python3.12-fabric-3.2.2
stripping (with command strip and flags -S) in  /nix/store/c10n2rxk9rgd6mh9nal9d5jv8q3ic32f-python3.12-fabric-3.2.2/lib /nix/store/c10n2rxk9rgd6mh9nal9d5jv8q3ic32f-python3.12-fabric-3.2.2/bin
checking for references to /private/tmp/nix-build-python3.12-fabric-3.2.2.drv-0/ in /nix/store/i0ifcnlxfga483zph6xdvb80f08j3jzw-python3.12-fabric-3.2.2-dist...
patching script interpreter paths in /nix/store/i0ifcnlxfga483zph6xdvb80f08j3jzw-python3.12-fabric-3.2.2-dist
Rewriting #!/nix/store/ybnf7k6i9p244bbhsbxizqk65z58cwyr-python3-3.12.6/bin/python3.12 to #!/nix/store/ybnf7k6i9p244bbhsbxizqk65z58cwyr-python3-3.12.6
wrapping `/nix/store/c10n2rxk9rgd6mh9nal9d5jv8q3ic32f-python3.12-fabric-3.2.2/bin/fab'...
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
Running phase: pythonCatchConflictsPhase
@nix { "action": "setPhase", "phase": "pythonCatchConflictsPhase" }
Running phase: pythonRemoveBinBytecodePhase
@nix { "action": "setPhase", "phase": "pythonRemoveBinBytecodePhase" }
Running phase: pythonImportsCheckPhase
@nix { "action": "setPhase", "phase": "pythonImportsCheckPhase" }
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: fabric
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/ybnf7k6i9p244bbhsbxizqk65z58cwyr-python3-3.12.6/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/nix/store/c10n2rxk9rgd6mh9nal9d5jv8q3ic32f-python3.12-fabric-3.2.2/lib/python3.12/site-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/nix/store/c10n2rxk9rgd6mh9nal9d5jv8q3ic32f-python3.12-fabric-3.2.2/lib/python3.12/site-packages/fabric/connection.py", line 9, in <module>
    from paramiko.agent import AgentRequestHandler
  File "/nix/store/7zmldqhzvg8dmq57g9x0z94kcz1qlnh7-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import (
  File "/nix/store/7zmldqhzvg8dmq57g9x0z94kcz1qlnh7-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/transport.py", line 99, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/nix/store/7zmldqhzvg8dmq57g9x0z94kcz1qlnh7-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
ModuleNotFoundError: No module named 'nacl'

`
looks to be related to: 
https://github.com/NixOS/nixpkgs/issues/350160

I'm a Nix novice (was hoping this would sell me) any tips to get round it gladly received.

**Comment by vfarcic** [comment]
I remember having that issue in the past and that it was related to Azure CLI. I thought I fixed it. Can you confirm that you are using the latest version of the repo? If you are, can you execute `nix-collect-garbage` first and then try again `nix-shell --run $SHELL`?

**Comment by tamingchaos** [comment]
Sorry @vfarcic, this appears to still be valid. I've performed a fresh install of Nix, and have confirmed I'm on the latest main, it was only forked this morning.

I have the same issue with `nix-shell -p azure-cli` so I would concur this is the culprit.

**Comment by vfarcic** [comment]
Hmmm... I could not reproduce it on my machines. I tried on Mac Studio and MacBook Pro (both with silicon chips) and it worked in both cases. Without being to reproduce it I'm not sure how to fix it :(

Which OS are you using? If it's something other than Mac with silicon chips, I can try to get the same and see what's going on.

**Comment by renaud-huillet** [comment]
I have the same problem running on WSL ubuntu on windows. I ended up removing the azure-cli and installing it sepqrqtely

**Comment by tamingchaos** [comment]
I'm on an M2 mac running MacOS 14.4.1, looks to be outside your control @vfarcic. nice tip @renaud-huillet
